// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.12.3
// source: geolocation-proxy.proto

package geolocationproto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CellTower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellId            int32 `protobuf:"varint,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	LocationAreaCode  int32 `protobuf:"varint,2,opt,name=location_area_code,json=locationAreaCode,proto3" json:"location_area_code,omitempty"`
	MobileCountryCode int32 `protobuf:"varint,3,opt,name=mobile_country_code,json=mobileCountryCode,proto3" json:"mobile_country_code,omitempty"`
	MobileNetworkCode int32 `protobuf:"varint,4,opt,name=mobile_network_code,json=mobileNetworkCode,proto3" json:"mobile_network_code,omitempty"`
	SignalStrength    int32 `protobuf:"varint,5,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
}

func (x *CellTower) Reset() {
	*x = CellTower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellTower) ProtoMessage() {}

func (x *CellTower) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellTower.ProtoReflect.Descriptor instead.
func (*CellTower) Descriptor() ([]byte, []int) {
	return file_geolocation_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *CellTower) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *CellTower) GetLocationAreaCode() int32 {
	if x != nil {
		return x.LocationAreaCode
	}
	return 0
}

func (x *CellTower) GetMobileCountryCode() int32 {
	if x != nil {
		return x.MobileCountryCode
	}
	return 0
}

func (x *CellTower) GetMobileNetworkCode() int32 {
	if x != nil {
		return x.MobileNetworkCode
	}
	return 0
}

func (x *CellTower) GetSignalStrength() int32 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

type WifiAccessPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddress         string  `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SignalStrength     float64 `protobuf:"fixed64,2,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	Channel            int32   `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	SignalToNoiseRatio float64 `protobuf:"fixed64,4,opt,name=signal_to_noise_ratio,json=signalToNoiseRatio,proto3" json:"signal_to_noise_ratio,omitempty"`
}

func (x *WifiAccessPoint) Reset() {
	*x = WifiAccessPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiAccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiAccessPoint) ProtoMessage() {}

func (x *WifiAccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiAccessPoint.ProtoReflect.Descriptor instead.
func (*WifiAccessPoint) Descriptor() ([]byte, []int) {
	return file_geolocation_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *WifiAccessPoint) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *WifiAccessPoint) GetSignalStrength() float64 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

func (x *WifiAccessPoint) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *WifiAccessPoint) GetSignalToNoiseRatio() float64 {
	if x != nil {
		return x.SignalToNoiseRatio
	}
	return 0
}

type GeolocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeMobileCountryCode int32              `protobuf:"varint,1,opt,name=home_mobile_country_code,json=homeMobileCountryCode,proto3" json:"home_mobile_country_code,omitempty"`
	HomeMobileNetworkCode int32              `protobuf:"varint,2,opt,name=home_mobile_network_code,json=homeMobileNetworkCode,proto3" json:"home_mobile_network_code,omitempty"`
	RadioType             string             `protobuf:"bytes,3,opt,name=radio_type,json=radioType,proto3" json:"radio_type,omitempty"`
	Carrier               string             `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
	CellTowers            []*CellTower       `protobuf:"bytes,5,rep,name=cellTowers,proto3" json:"cellTowers,omitempty"`
	WifiAccessPoints      []*WifiAccessPoint `protobuf:"bytes,6,rep,name=wifiAccessPoints,proto3" json:"wifiAccessPoints,omitempty"`
}

func (x *GeolocationRequest) Reset() {
	*x = GeolocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeolocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeolocationRequest) ProtoMessage() {}

func (x *GeolocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeolocationRequest.ProtoReflect.Descriptor instead.
func (*GeolocationRequest) Descriptor() ([]byte, []int) {
	return file_geolocation_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *GeolocationRequest) GetHomeMobileCountryCode() int32 {
	if x != nil {
		return x.HomeMobileCountryCode
	}
	return 0
}

func (x *GeolocationRequest) GetHomeMobileNetworkCode() int32 {
	if x != nil {
		return x.HomeMobileNetworkCode
	}
	return 0
}

func (x *GeolocationRequest) GetRadioType() string {
	if x != nil {
		return x.RadioType
	}
	return ""
}

func (x *GeolocationRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *GeolocationRequest) GetCellTowers() []*CellTower {
	if x != nil {
		return x.CellTowers
	}
	return nil
}

func (x *GeolocationRequest) GetWifiAccessPoints() []*WifiAccessPoint {
	if x != nil {
		return x.WifiAccessPoints
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_geolocation_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type GeolocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Accuracy float64   `protobuf:"fixed64,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
}

func (x *GeolocationResponse) Reset() {
	*x = GeolocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geolocation_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeolocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeolocationResponse) ProtoMessage() {}

func (x *GeolocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geolocation_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeolocationResponse.ProtoReflect.Descriptor instead.
func (*GeolocationResponse) Descriptor() ([]byte, []int) {
	return file_geolocation_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *GeolocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GeolocationResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

var File_geolocation_proxy_proto protoreflect.FileDescriptor

var file_geolocation_proxy_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x65, 0x6f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x09,
	0x43, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x6c,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x72, 0x65, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0xa8, 0x01, 0x0a, 0x0f, 0x57, 0x69,
	0x66, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x31, 0x0a, 0x15, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x5f, 0x6e,
	0x6f, 0x69, 0x73, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54, 0x6f, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x52,
	0x61, 0x74, 0x69, 0x6f, 0x22, 0xcb, 0x02, 0x0a, 0x12, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x68,
	0x6f, 0x6d, 0x65, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x18, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x68, 0x6f, 0x6d, 0x65, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x65, 0x6c, 0x6c, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x65, 0x6f,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x65,
	0x6c, 0x6c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x65, 0x6c, 0x6c, 0x54, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x10, 0x77, 0x69, 0x66, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x57, 0x69, 0x66, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x10, 0x77, 0x69, 0x66, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x6e, 0x67, 0x22, 0x69, 0x0a, 0x13, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65,
	0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x32, 0x6e, 0x0a,
	0x10, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x12, 0x5a, 0x0a, 0x09, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x12, 0x24,
	0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a,
	0x12, 0x2e, 0x3b, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geolocation_proxy_proto_rawDescOnce sync.Once
	file_geolocation_proxy_proto_rawDescData = file_geolocation_proxy_proto_rawDesc
)

func file_geolocation_proxy_proto_rawDescGZIP() []byte {
	file_geolocation_proxy_proto_rawDescOnce.Do(func() {
		file_geolocation_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_geolocation_proxy_proto_rawDescData)
	})
	return file_geolocation_proxy_proto_rawDescData
}

var file_geolocation_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geolocation_proxy_proto_goTypes = []interface{}{
	(*CellTower)(nil),           // 0: geolocationproto.CellTower
	(*WifiAccessPoint)(nil),     // 1: geolocationproto.WifiAccessPoint
	(*GeolocationRequest)(nil),  // 2: geolocationproto.GeolocationRequest
	(*Location)(nil),            // 3: geolocationproto.Location
	(*GeolocationResponse)(nil), // 4: geolocationproto.GeolocationResponse
}
var file_geolocation_proxy_proto_depIdxs = []int32{
	0, // 0: geolocationproto.GeolocationRequest.cellTowers:type_name -> geolocationproto.CellTower
	1, // 1: geolocationproto.GeolocationRequest.wifiAccessPoints:type_name -> geolocationproto.WifiAccessPoint
	3, // 2: geolocationproto.GeolocationResponse.location:type_name -> geolocationproto.Location
	2, // 3: geolocationproto.GeolocationProxy.Geolocate:input_type -> geolocationproto.GeolocationRequest
	4, // 4: geolocationproto.GeolocationProxy.Geolocate:output_type -> geolocationproto.GeolocationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geolocation_proxy_proto_init() }
func file_geolocation_proxy_proto_init() {
	if File_geolocation_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geolocation_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellTower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiAccessPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeolocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geolocation_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeolocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geolocation_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geolocation_proxy_proto_goTypes,
		DependencyIndexes: file_geolocation_proxy_proto_depIdxs,
		MessageInfos:      file_geolocation_proxy_proto_msgTypes,
	}.Build()
	File_geolocation_proxy_proto = out.File
	file_geolocation_proxy_proto_rawDesc = nil
	file_geolocation_proxy_proto_goTypes = nil
	file_geolocation_proxy_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeolocationProxyClient is the client API for GeolocationProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeolocationProxyClient interface {
	Geolocate(ctx context.Context, in *GeolocationRequest, opts ...grpc.CallOption) (*GeolocationResponse, error)
}

type geolocationProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewGeolocationProxyClient(cc grpc.ClientConnInterface) GeolocationProxyClient {
	return &geolocationProxyClient{cc}
}

func (c *geolocationProxyClient) Geolocate(ctx context.Context, in *GeolocationRequest, opts ...grpc.CallOption) (*GeolocationResponse, error) {
	out := new(GeolocationResponse)
	err := c.cc.Invoke(ctx, "/geolocationproto.GeolocationProxy/Geolocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeolocationProxyServer is the server API for GeolocationProxy service.
type GeolocationProxyServer interface {
	Geolocate(context.Context, *GeolocationRequest) (*GeolocationResponse, error)
}

// UnimplementedGeolocationProxyServer can be embedded to have forward compatible implementations.
type UnimplementedGeolocationProxyServer struct {
}

func (*UnimplementedGeolocationProxyServer) Geolocate(context.Context, *GeolocationRequest) (*GeolocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geolocate not implemented")
}

func RegisterGeolocationProxyServer(s *grpc.Server, srv GeolocationProxyServer) {
	s.RegisterService(&_GeolocationProxy_serviceDesc, srv)
}

func _GeolocationProxy_Geolocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeolocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeolocationProxyServer).Geolocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geolocationproto.GeolocationProxy/Geolocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeolocationProxyServer).Geolocate(ctx, req.(*GeolocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeolocationProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geolocationproto.GeolocationProxy",
	HandlerType: (*GeolocationProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geolocate",
			Handler:    _GeolocationProxy_Geolocate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geolocation-proxy.proto",
}
